language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - pytest --cov=app --cov-fail-under=100

after_success:
  - codecov

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: web-ozon